In [ ]:
# Diagonal Difference

In [1]:
import numpy as np

In [ ]:
3
11 2 4
4 5 6
10 8 -12

In [78]:
list=[11,2,4,4,5,6,10,8,-12]
arr=np.array(list)
arr=arr.reshape(3,3)
arr

array([[ 11,   2,   4],
       [  4,   5,   6],
       [ 10,   8, -12]])

In [61]:
list

[11, 2, 4, 4, 5, 6, 10, 8, -12]

In [69]:
def diagonalDifference(list):
    n=len(arr[0])
    d=0
    e=0
    for i in range(n):
        d+=arr[i][i]
        e+=arr[i][n-i-1]
    return abs(abs(d)-abs(e))

In [70]:
diagonalDifference(list)

15

In [71]:
for j in range(3-1,-1,-1):
    print(j)

2
1
0


In [18]:
arr[0][-1]

11

In [ ]:
|4 - 19| = 15

In [8]:
shape=arr.shape
n=shape[0]
n

3

In [17]:
list=[]
for x in range(n):
    list.append(x)  
print(list)


[0, 1, 2]


In [72]:
arr

array([[ 11,   2,   4],
       [  4,   5,   6],
       [ 10,   8, -12]])

In [79]:

arr.reshape(1,arr.size)

array([[ 11,   2,   4,   4,   5,   6,  10,   8, -12]])

In [81]:
arr.sum()

38

In [103]:
def miniMaxSum(arr):
    new_arr=arr.reshape(1,arr.size)
    x=[] 
    for z in  range(len(new_arr)):
        x.append(arr.sum()-new_arr[z])
        print(x)
    return min(x), max(x) 

In [104]:
miniMaxSum(arr)

[array([27, 36, 34, 34, 33, 32, 28, 30, 50])]


(array([27, 36, 34, 34, 33, 32, 28, 30, 50]),
 array([27, 36, 34, 34, 33, 32, 28, 30, 50]))